jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false  # Позволяет другим job'ам выполняться независимо

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Обновлённая версия

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3  # Обновлённая версия
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'  # Кэширование yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
        continue-on-error: true  # Продолжать даже при ошибках линтинга

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build